---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Upload file to qumulo
      qumulo_upload:
        user: "{{ qumulo_user }}"
        password: "{{ qumulo_password }}"
        cluster_address: "{{ qumulo_address }}"
        src: "myfile.txt"
        dest: "/keyva_demo/newdir/extra_dir/myfile.txt"